// interop_test.go — Cross-runtime golden tests for AES-256-GCM settings tokens.
//
// Reads internal/testdata/golden/encryption.json and asserts that every
// committed token decrypts to the recorded plaintext under the recorded key.
//
// The fixture is regenerated by scripts/regen-golden.go. Python-produced
// entries (added in the paired omkit-python PR) carry produced_by="py" and
// pin the bidirectional contract: tokens written by either SDK MUST be
// readable from both.
//
// Counterpart in Python: omkit-python/tests/test_encryption_interop.py reads
// the same JSON file.

package encryption

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

type encryptionGoldenCase struct {
	Name       string `json:"name"`
	KeyB64     string `json:"key_b64"`
	Token      string `json:"token"`
	Plaintext  string `json:"plaintext"`
	ProducedBy string `json:"produced_by"`
}

func loadEncryptionGolden(t *testing.T) []encryptionGoldenCase {
	t.Helper()
	path := filepath.Join("..", "internal", "testdata", "golden", "encryption.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var cases []encryptionGoldenCase
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(cases) == 0 {
		t.Fatal("golden file has no cases")
	}
	return cases
}

func TestGolden_EncryptionDecrypt(t *testing.T) {
	for _, c := range loadEncryptionGolden(t) {
		t.Run(c.Name, func(t *testing.T) {
			got, err := Decrypt(c.Token, c.KeyB64)
			if err != nil {
				t.Fatalf("decrypt (produced_by=%s): %v", c.ProducedBy, err)
			}
			if got != c.Plaintext {
				t.Fatalf("plaintext drift (produced_by=%s):\n got: %q\nwant: %q", c.ProducedBy, got, c.Plaintext)
			}
		})
	}
}
